---
title: "DS 2020 - lab #2: exploring residential sales in Ames"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

In this activity we are going to explore a data set and write-up our findings in a team-edited report.



---

# Getting Ready

1. Identify your team! Go to Canvas and find out which team you are in for Lab 2. 

2. Find the other members of your team and sit with them.

3. Introduce yourself to each other. 

4. Go to https://ds202-at-isu.github.io/labs/lab02.html and follow the instructions.

---

# Create Your Lab Repo in Github Classroom

Accept the link to Github Classroom shared in the announcement.
  
  - This link will ask you to log in to GitHub. Select your name from the list by clicking on it.  

  - Check if your team number already exists - if it does, join the team with the right number. If it doesn't exist yet, create it yourself.

---

# Overall aim of this lab:
  
- Residential sales of properties in Ames since 2017 (`ames`) are made available as part of the `classdata` package. You are asked to explore the data set as a group and write up your findings.

- Describe your findings: each team member is asked to follow through with one line of investigation/exploration. Document your findings in text, code and in pictures. 

- Collect all of your experiences and make it into one cohesive document. Use the **README.Rmd** file of the lab-2 repo for this document. 

- Knit **README.Rmd** to update **README.md**. Push changes of both **README.Rmd** and **README.md** to your repo. 

- Write a TL;DR at the front of the document summarising your findings.

---

# What You Need to Do

1. inspect the first few lines of the data set: 

  - what variables are there? of what type are the variables? what does each variable mean? what do we expect their data range to be?

2. is there a variable of special interest or focus? Let's call it the "main variable"

3. start the exploration with the main variable: 

  - what is the range of this variable? draw a histogram for a numeric variable or a bar chart, if the variable is categorical. what is the general pattern? is there anything odd? 
  - follow-up on oddities: see 4

4. pick a variable that might be related to the main variable. 

  - what is the range of that variable? plot. describe the pattern.
  - what is the relationship to the main variable? plot a scatterplot, boxplot or facetted barcharts (dependening on the types of variables involved). Describe overall pattern, does this variable describe any oddities discovered in 3? Identify/follow-up on any oddities. 

---

# Procedure

The main variable for this exploration is `Sale Price`. **As a team**, do steps 1 through 3. Document your findings in the README.Rmd of the lab's repo.

**As a team**, discuss different lines of investigation (step 4) and agree on who is doing which investigation. 
Make a note of who is doing what in the README.Rmd

**Individually:** follow through with your line of investigation. Include at least one plot that describes the relationship between sales prices and your variable. Include one paragraph describing the pattern you see. Are there oddities? Follow-up on (some of) them.

---

# Example Final README.Rmd

### step 1 result

As a team, we found that ...

### step 2 result

As a team, we found that ...

### step 3 result

As a team, we found that ...

### step 4 result

Will's work: 

Craig's work:


---

# Grading & Submission


**Grading:** We expect equal contributions from all members in a team. For the grading we will make use of the github commit history to verify that everybody contributed. 

*There will be differential grades, if necessary* 

**Submission:**
All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.


Due date: You have time until Monday at 11:59 pm to submit final edits to the README.Rmd file. Make sure that the file knits.
